baseURL = "https://sipcraftbeer.com"
languageCode = "en-us"
title = "Sip Craft Beer"
theme = "hugo-sugoi"
publishDir = "docs"
googleAnalytics = "UA-177014336-1"

[params]
herotitle = "Sip Craft Beer"
herolink = "post"
herolinktext = "Read them All"
author = "Jon Johnson"


[hero]

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-home'></i>"
        url     = "about"
        weight  = -1
    [[menu.nav]]
        name  = "contact"
        pre = "<i class='far fa-envelope-open'></i>"
        url     = "contact"
        weight  = -1    
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "post"
        weight  = -2